remote_theme: pmarsceill/just-the-docs
title: Hodaie Lab Training Manual
description: Hodaie Lab Training Manual
baseurl: "/lab_wiki"
url: "https://hodaielab.github.io"
aux_links:
  "Lab Website":
    - "//hodaielab.com"
  "Lab Papers":
      - "//www.hodaielab.com/publications.html"
aux_links_new_tab: true
