remote_theme: pmarsceill/just-the-docs
title: Hodaie Lab Wiki
description: Collection of information on data processing and resources.
baseurl: "/hodaielab_wiki"
url: "https://hodaielab.github.io"
aux_links:
  "Lab Website":
    - "//hodaielab.com"
  "Lab Papers":
      - "//www.hodaielab.com/publications.html"
aux_links_new_tab: true
